//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Common.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Common.Languages.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đã bị khóa.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không thuộc phòng sở.
        /// </summary>
        public static string AccountNotAssignManagementUnit {
            get {
                return ResourceManager.GetString("AccountNotAssignManagementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không xác định.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ quyền.
        /// </summary>
        public static string AccountNotPermission {
            get {
                return ResourceManager.GetString("AccountNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tỉ.
        /// </summary>
        public static string BillionUnit {
            get {
                return ResourceManager.GetString("BillionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mươi.
        /// </summary>
        public static string DozenUnit {
            get {
                return ResourceManager.GetString("DozenUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tám.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to năm.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lăm.
        /// </summary>
        public static string FiveUnit {
            get {
                return ResourceManager.GetString("FiveUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bốn.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trăm.
        /// </summary>
        public static string HundredUnit {
            get {
                return ResourceManager.GetString("HundredUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triệu.
        /// </summary>
        public static string MillionUnit {
            get {
                return ResourceManager.GetString("MillionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chín.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lẻ.
        /// </summary>
        public static string Odd {
            get {
                return ResourceManager.GetString("Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to một.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mốt.
        /// </summary>
        public static string OneUnit {
            get {
                return ResourceManager.GetString("OneUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bảy.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sáu.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mười.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mươi.
        /// </summary>
        public static string TenUnit {
            get {
                return ResourceManager.GetString("TenUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nghìn.
        /// </summary>
        public static string ThousandUnit {
            get {
                return ResourceManager.GetString("ThousandUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hai.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không xác định.
        /// </summary>
        public static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đồng.
        /// </summary>
        public static string VNDUnit {
            get {
                return ResourceManager.GetString("VNDUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
