//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Domain.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} đã bị khóa..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này chưa được chỉ định đơn vị trực thuộc..
        /// </summary>
        public static string AccountNotAssignManagementUnit {
            get {
                return ResourceManager.GetString("AccountNotAssignManagementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} chưa được cấp quyền để truy cập!.
        /// </summary>
        public static string AccountNotPermission {
            get {
                return ResourceManager.GetString("AccountNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mượn trả.
        /// </summary>
        public static string BorrowPublication {
            get {
                return ResourceManager.GetString("BorrowPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu đã được trả.
        /// </summary>
        public static string BorrowPublicationIsReturned {
            get {
                return ResourceManager.GetString("BorrowPublicationIsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu mượn không tồn tại.
        /// </summary>
        public static string BorrowPublicationNotFound {
            get {
                return ResourceManager.GetString("BorrowPublicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả đã tồn tại!.
        /// </summary>
        public static string CadreExisted {
            get {
                return ResourceManager.GetString("CadreExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả đã tồn tại trên hệ thống. Bạn không thể thêm mới tác giả này.
        /// </summary>
        public static string CadreExistedMessage {
            get {
                return ResourceManager.GetString("CadreExistedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ không tồn tại.
        /// </summary>
        public static string CadreNotFound {
            get {
                return ResourceManager.GetString("CadreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa phiếu mượn có ấn phẩm đã trả.
        /// </summary>
        public static string CannotDeleteBorrowPublicationHavePublicationReturned {
            get {
                return ResourceManager.GetString("CannotDeleteBorrowPublicationHavePublicationReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thao tác trên nhà xuất bản của hệ thống !.
        /// </summary>
        public static string CannotOperatePublishingHouseSystem {
            get {
                return ResourceManager.GetString("CannotOperatePublishingHouseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thao tác trên kho của hệ thống.
        /// </summary>
        public static string CannotUpdateIsStockSystem {
            get {
                return ResourceManager.GetString("CannotUpdateIsStockSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thao tác trên môn loại của hệ thống.
        /// </summary>
        public static string CannotUpdateIsSubjectKindSystem {
            get {
                return ResourceManager.GetString("CannotUpdateIsSubjectKindSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp học đã tồn tại.
        /// </summary>
        public static string ClassIsExisted {
            get {
                return ResourceManager.GetString("ClassIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp học không tồn tại.
        /// </summary>
        public static string ClassNotFound {
            get {
                return ResourceManager.GetString("ClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        public static string EmailAlreadyExisted {
            get {
                return ResourceManager.GetString("EmailAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đợt kiểm kê này đang trùng với đợt kiểm kê trước, vui lòng chọn lại!.
        /// </summary>
        public static string ExistInventoryVoucherRangeOfDate {
            get {
                return ResourceManager.GetString("ExistInventoryVoucherRangeOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại mã ĐKCB đang phát sinh nghiệp vụ {0}.
        /// </summary>
        public static string ExsitParticularBusinessArises {
            get {
                return ResourceManager.GetString("ExsitParticularBusinessArises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin này là bắt buộc.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh mã ĐKCB.
        /// </summary>
        public static string GenerateParticularCode {
            get {
                return ResourceManager.GetString("GenerateParticularCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ấn phẩm {0}.
        /// </summary>
        public static string GeneratePublicationCode {
            get {
                return ResourceManager.GetString("GeneratePublicationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không đúng..
        /// </summary>
        public static string InputDataIsWrong {
            get {
                return ResourceManager.GetString("InputDataIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê.
        /// </summary>
        public static string InventoryVoucher {
            get {
                return ResourceManager.GetString("InventoryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết kiểm kê không tồn tại.
        /// </summary>
        public static string InventoryVoucherDetailINotFound {
            get {
                return ResourceManager.GetString("InventoryVoucherDetailINotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu kiểm kê không tồn tại.
        /// </summary>
        public static string InventoryVoucherNotFound {
            get {
                return ResourceManager.GetString("InventoryVoucherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh lý.
        /// </summary>
        public static string Liquidate {
            get {
                return ResourceManager.GetString("Liquidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thanh lý.
        /// </summary>
        public static string LiquidateCode {
            get {
                return ResourceManager.GetString("LiquidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thanh lý không được nhỏ hơn ngày chứng từ!.
        /// </summary>
        public static string LiquidatedDateSmallDateOfVouchers {
            get {
                return ResourceManager.GetString("LiquidatedDateSmallDateOfVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu thanh lý {0} phát sinh .
        /// </summary>
        public static string LiquidateHasParticularCodeBussiness {
            get {
                return ResourceManager.GetString("LiquidateHasParticularCodeBussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh lý không tồn tại.
        /// </summary>
        public static string LiquidateNotFound {
            get {
                return ResourceManager.GetString("LiquidateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không hợp lệ!.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình tham số đã tồn tại.
        /// </summary>
        public static string ManagementTypeParameterExisted {
            get {
                return ResourceManager.GetString("ManagementTypeParameterExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình hệ thống không tồn tại.
        /// </summary>
        public static string ManagementTypeParameterNotFound {
            get {
                return ResourceManager.GetString("ManagementTypeParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã phát sinh nghiệp vụ.
        /// </summary>
        public static string NoneBusinessArises {
            get {
                return ResourceManager.GetString("NoneBusinessArises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sách ĐKCB {0} đã phát sinh nghiệp vụ.
        /// </summary>
        public static string NoneParticularCodeArises {
            get {
                return ResourceManager.GetString("NoneParticularCodeArises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm học cũ không tồn tại.
        /// </summary>
        public static string OldSchoolYearNotFound {
            get {
                return ResourceManager.GetString("OldSchoolYearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đăng kí cá biệt đã tồn tại.
        /// </summary>
        public static string ParticularCodeExisted {
            get {
                return ResourceManager.GetString("ParticularCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ĐKCB không tồn tại.
        /// </summary>
        public static string ParticularCodeNotFound {
            get {
                return ResourceManager.GetString("ParticularCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} có phiếu mượn trả {1} ngày {2}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessBorrow {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ĐKCB {0} đã phát sinh nghiệp vụ {1}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessDetail {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} có kiểm kê ngày {1}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessInventoryVoucher {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessInventoryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} có thanh lý {1} ngày {2}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessLiquidate {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessLiquidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} có hồi cố ngày {1}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessRetrospective {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessRetrospective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} có chứng từ {1} ngày {2}.
        /// </summary>
        public static string ParticularCodeNotifyBusinessVoucher {
            get {
                return ResourceManager.GetString("ParticularCodeNotifyBusinessVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm đã được cho mượn từ trước!.
        /// </summary>
        public static string PublicationDetailHasBorrowing {
            get {
                return ResourceManager.GetString("PublicationDetailHasBorrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm đã được thanh lý từ trước!.
        /// </summary>
        public static string PublicationDetailHasLiquidated {
            get {
                return ResourceManager.GetString("PublicationDetailHasLiquidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy ấn phẩm.
        /// </summary>
        public static string PublicationDetailNotFound {
            get {
                return ResourceManager.GetString("PublicationDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái {0} không hợp lệ.
        /// </summary>
        public static string PublicationDetailStatusInvalid {
            get {
                return ResourceManager.GetString("PublicationDetailStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm đã tồn tại trong danh sách kiểm kê.
        /// </summary>
        public static string PublicationExistedInInventoryVoucherDetail {
            get {
                return ResourceManager.GetString("PublicationExistedInInventoryVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm đã tồn tại.
        /// </summary>
        public static string PublicationIsExisted {
            get {
                return ResourceManager.GetString("PublicationIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm không tồn tại.
        /// </summary>
        public static string PublicationNotFound {
            get {
                return ResourceManager.GetString("PublicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm {0} đã phát sinh nghiệp vụ {1}.
        /// </summary>
        public static string PublicationNotifyBusinessDetail {
            get {
                return ResourceManager.GetString("PublicationNotifyBusinessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồi cố.
        /// </summary>
        public static string PublicationRetrospective {
            get {
                return ResourceManager.GetString("PublicationRetrospective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin hồi cố của ấn phẩm.
        /// </summary>
        public static string PublicationRetrospectiveNotFound {
            get {
                return ResourceManager.GetString("PublicationRetrospectiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà xuất bản đã tồn tại!.
        /// </summary>
        public static string PublishingHouseExisted {
            get {
                return ResourceManager.GetString("PublishingHouseExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà xuất bản không tồn tại.
        /// </summary>
        public static string PublishingHouseNotFound {
            get {
                return ResourceManager.GetString("PublishingHouseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh chưa được phân lớp.
        /// </summary>
        public static string PupilNotDivideClass {
            get {
                return ResourceManager.GetString("PupilNotDivideClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh không tồn tại.
        /// </summary>
        public static string PupilNotFound {
            get {
                return ResourceManager.GetString("PupilNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ bạn đọc không tồn tại.
        /// </summary>
        public static string ReaderCardNotFound {
            get {
                return ResourceManager.GetString("ReaderCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản báo cáo không tồn tại.
        /// </summary>
        public static string ReportVersionNotfound {
            get {
                return ResourceManager.GetString("ReportVersionNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hẹn trả phải lớn hơn hoặc bằng ngày mượn.
        /// </summary>
        public static string RequirementDateMustEqualGreaterBorrowDate {
            get {
                return ResourceManager.GetString("RequirementDateMustEqualGreaterBorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hồi cố không được nhỏ hơn ngày thanh lý {0}.
        /// </summary>
        public static string RetrospectiveDateMustEqualOrGreaterThanLiquidatedDate {
            get {
                return ResourceManager.GetString("RetrospectiveDateMustEqualOrGreaterThanLiquidatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã trường học đã tồn tại!.
        /// </summary>
        public static string SchoolCodeExisted {
            get {
                return ResourceManager.GetString("SchoolCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm học không tồn tại.
        /// </summary>
        public static string SchoolYearNotFound {
            get {
                return ResourceManager.GetString("SchoolYearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống bị lỗi, vui lòng thử lại sau!.
        /// </summary>
        public static string SomethingIsWrong {
            get {
                return ResourceManager.GetString("SomethingIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hoặc tên kho đã tồn tại.
        /// </summary>
        public static string StockNameOrCodeExisted {
            get {
                return ResourceManager.GetString("StockNameOrCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho không tồn tại.
        /// </summary>
        public static string StockNotFound {
            get {
                return ResourceManager.GetString("StockNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có giao viên sử dụng dữ liệu này, bạn không thể ngưng hoạt động.
        /// </summary>
        public static string SubjectKindDontUsedByCadre {
            get {
                return ResourceManager.GetString("SubjectKindDontUsedByCadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hoặc tên môn loại đã tồn tại.
        /// </summary>
        public static string SubjectKindNameOrCodeExisted {
            get {
                return ResourceManager.GetString("SubjectKindNameOrCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn loại không tồn tại.
        /// </summary>
        public static string SubjectKindNotFound {
            get {
                return ResourceManager.GetString("SubjectKindNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ bộ môn đã tồn tại!.
        /// </summary>
        public static string SubjectTeamExisted {
            get {
                return ResourceManager.GetString("SubjectTeamExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ bộ môn không tồn tại.
        /// </summary>
        public static string SubjectTeamNotFound {
            get {
                return ResourceManager.GetString("SubjectTeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} không xác định.
        /// </summary>
        public static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không xác định.
        /// </summary>
        public static string UserUnknown02 {
            get {
                return ResourceManager.GetString("UserUnknown02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ.
        /// </summary>
        public static string VoucherCode {
            get {
                return ResourceManager.GetString("VoucherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ đã tồn tại.
        /// </summary>
        public static string VoucherCodeExisted {
            get {
                return ResourceManager.GetString("VoucherCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn phẩm không được trùng.
        /// </summary>
        public static string VoucherDetailCannotDuplicate {
            get {
                return ResourceManager.GetString("VoucherDetailCannotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ không tồn tại.
        /// </summary>
        public static string VoucherNotFound {
            get {
                return ResourceManager.GetString("VoucherNotFound", resourceCulture);
            }
        }
    }
}
